// src/utils/jobCategories.js
export const jobCategories = [
  "Software Developer",
  "UI/UX Designer",
  "Graphic Designer",
  "Data Analyst",
  "Digital Marketer",
  "Sales Executive",
  "Content Writer",
  "Customer Support",
  "Finance Manager",
  "Human Resources",
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrician",
  "Plumber",
  "Teacher",
  "Doctor",
  "Nurse",
  'Software Development',
  'Design',
  'Marketing',
  'Sales',
  'Customer Support',
  'Finance',
  'Human Resources',
  "Programming",
  "Data Science",
  "Designing",
  "Networking",
  "Management",
  "Marketing",
  "Cybersecurity"
];
